spring:
  application:
    name: operation-service
  datasource:
    url: jdbc:mysql://localhost:3306/profiledb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8200